#!/usr/bin/env python3
"""Make AOTInductor-compiled Metal models load, and compute correctly, on
machines other than the one that exported them.

An ExecuTorch Metal ``.pte`` embeds a shared object compiled by AOTInductor.
Two inductor defaults break such a model once it leaves the export machine, and
``portable_aoti_shared_object`` turns both off for the duration of an export.

1. OpenMP. Inductor links the object against OpenMP unconditionally, and on
   macOS the libomp it finds is the one inside the PyTorch wheel, whose install
   name is the absolute path ``/opt/llvm-openmp/lib/libomp.dylib``. That path
   exists on no end-user machine, so the runtime's ``dlopen`` failed with
   ``Library not loaded: /opt/llvm-openmp/lib/libomp.dylib``. The dependency is
   dead weight: a Metal-delegated graph runs on the GPU and the generated
   wrapper references no OpenMP symbol. Inductor has no switch to skip it, but
   it does let the compiler be chosen (``cpp.cxx``), so the export runs behind
   a thin compiler wrapper that adds ``-dead_strip_dylibs``. The linker then
   drops every dylib the object does not actually use, and keeps libomp if a
   model ever does need it, in which case the check below fails the export
   instead of shipping a model that cannot load. Reported upstream as
   pytorch/executorch#22955.

2. Layout optimization. For graphs with convolutions inductor converts
   activations and weights to channels-last and calls the convolution with
   channels-last strides. ExecuTorch's Metal convolution kernel
   (``aoti_torch_mps_convolution``) ignores strides and reads the memory as
   contiguous NCHW, so every conv2d inductor does not lower to a matmul returns
   wrong values: MobileNet exported this way ran but was confidently wrong
   (top-1 logit 3094 where PyTorch says 8.1). With ``layout_optimization`` off
   the tensors stay contiguous and the outputs match eager to 1e-6. Drop this
   once the runtime we ship has the upstream fix (pytorch/executorch#22951).
"""

import contextlib
import os
import shutil
import stat
import subprocess
import tempfile
from typing import Iterator, List

# Only libraries that ship with macOS are guaranteed to exist where the model
# is loaded.
_PORTABLE_PREFIXES = ("/usr/lib/", "/System/Library/")

_WRAPPER_TEMPLATE = """#!/bin/sh
# Generated by portable_aoti.py. Adds -dead_strip_dylibs to link steps only.
# Anything that does not link (compile-only, precompiled headers, version
# queries) must pass through untouched: there the extra flag counts as a second
# input and clang refuses to combine it with -o.
for arg in "$@"; do
  case "$arg" in
    -c|-E|-S|*-header|--version|-v|-dumpversion|-dumpmachine) exec "{cxx}" "$@" ;;
  esac
done
exec "{cxx}" "$@" -Wl,-dead_strip_dylibs
"""


def non_portable_dependencies(so_path: str) -> List[str]:
    """Dylibs ``so_path`` links that a user's machine is not guaranteed to have."""
    own_id = subprocess.run(
        ["otool", "-D", so_path], check=True, capture_output=True, text=True
    ).stdout.splitlines()[1:]
    listed = subprocess.run(
        ["otool", "-L", so_path], check=True, capture_output=True, text=True
    ).stdout.splitlines()[1:]
    dependencies = [line.split(" (compatibility")[0].strip() for line in listed]
    return [
        dep
        for dep in dependencies
        if dep and dep not in own_id and not dep.startswith(_PORTABLE_PREFIXES)
    ]


def _clear_inductor_compiler_cache() -> None:
    """Inductor memoizes the compiler it picked; make it look again."""
    from torch._inductor import cpp_builder

    cache_clear = getattr(cpp_builder.get_cpp_compiler, "cache_clear", None)
    if cache_clear is not None:
        cache_clear()


@contextlib.contextmanager
def portable_aoti_shared_object() -> Iterator[None]:
    """Export Metal models that load and compute correctly on other machines.

    Wrap the lowering call (``to_edge_transform_and_lower``) in this. It fails
    the export if the compiled object still depends on anything outside the OS.
    See the module docstring for the two inductor defaults it overrides.
    """
    from executorch.backends.apple.metal.metal_backend import MetalBackend
    from torch._inductor import config as inductor_config

    # Inductor reads CXX once, when torch is imported, so setting the variable
    # here would be too late; go through its config instead. Entries may be
    # None ("fetch a compiler from conda"), so take the first real one.
    configured = inductor_config.cpp.cxx
    if not isinstance(configured, (list, tuple)):
        configured = (configured,)
    real_cxx = next((c for c in configured if c), None) or "clang++"
    real_cxx = shutil.which(real_cxx) or real_cxx
    wrapper_dir = tempfile.mkdtemp(prefix="portable_aoti_")
    wrapper = os.path.join(wrapper_dir, "cxx")
    with open(wrapper, "w") as f:
        f.write(_WRAPPER_TEMPLATE.format(cxx=real_cxx))
    os.chmod(wrapper, os.stat(wrapper).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    # ExecuTorch calls this hook on the compiled object right before reading
    # its bytes into the .pte, which makes it the one place the final object
    # can be inspected.
    original_hook = MetalBackend.__dict__.get("codesign_so")
    if original_hook is None:
        raise RuntimeError(
            "MetalBackend.codesign_so is missing in this ExecuTorch version, so the "
            "compiled Metal object cannot be checked for non-portable dependencies."
        )

    def checked_codesign_so(cls, so_path, compile_specs):
        original_hook.__func__(cls, so_path, compile_specs)
        leftovers = non_portable_dependencies(so_path)
        if leftovers:
            raise RuntimeError(
                "The compiled Metal object links libraries that will not exist where "
                f"the model is loaded: {leftovers}. It would fail to dlopen on every "
                "machine but this one. If it genuinely uses OpenMP, the model cannot "
                "be distributed as a Metal export as is."
            )

    MetalBackend.codesign_so = classmethod(checked_codesign_so)
    _clear_inductor_compiler_cache()
    try:
        with inductor_config.patch(
            {"cpp.cxx": (wrapper,), "layout_optimization": False}
        ):
            yield
    finally:
        MetalBackend.codesign_so = original_hook
        _clear_inductor_compiler_cache()
        shutil.rmtree(wrapper_dir, ignore_errors=True)
